import Head from 'next/head'
import Image from 'next/image'

import Header from '@/components/global/Header'
import Footer from '@/components/global/Footer'
import Board from '@/components/Board'

export default function Home() {
  return (
    <>
      <Head>
        <title>Joy-OAT Whiteboard</title>
        <meta name="description" content="Drawing app generated by create next app, fabric.js, and React.js" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Board />
      <Footer />
    </>
  )
}
